# Generated by Django 6.1 on 2026-08-15 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('naqd', 'Naqd'), ('karta', 'Karta'), ('bank', 'Bank')], default='naqd', max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('next_payment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('paid', "To'landi"), ('unpaid', "To'lamadi"), ('partial', 'Qisman')], default='paid', max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='teachers.teacher')),
            ],
        ),
    ]
